apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: grafana
      targetRevision: 9.0.0
      helm:
        valueFiles:
          - $values/grafana/values.yaml
    - repoURL: "https://github.com/Tech-Preta/gitops-with-argocd.git"
      targetRevision: feat/day2
      ref: values
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
