datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: https://prom.nataliagranato.xyz
        access: proxy
        isDefault: true
